/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ItemCard: typeof import('./components/to-do/ItemCard.vue')['default']
    ItemInfo: typeof import('./components/to-do/ItemInfo.vue')['default']
    ItemList: typeof import('./components/to-do/ItemList.vue')['default']
    ItemStore: typeof import('./components/to-do/ItemStore.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoreItem: typeof import('./components/to-do/StoreItem.vue')['default']
    TAlert: typeof import('./components/core/TAlert.vue')['default']
    TAppBar: typeof import('./components/core/TAppBar.vue')['default']
    TButton: typeof import('./components/core/TButton.vue')['default']
    TCard: typeof import('./components/core/TCard.vue')['default']
    TDateInput: typeof import('./components/form/TDateInput.vue')['default']
    TDatetimeInput: typeof import('./components/form/TDatetimeInput.vue')['default']
    TEmailInput: typeof import('./components/form/TEmailInput.vue')['default']
    TPasswordInput: typeof import('./components/form/TPasswordInput.vue')['default']
    TSnackbar: typeof import('./components/core/TSnackbar.vue')['default']
    TTextInput: typeof import('./components/core/TTextInput.vue')['default']
  }
}
