/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/auth/auth-view': RouteRecordInfo<'/auth/auth-view', '/auth/auth-view', Record<never, never>, Record<never, never>>,
    '/auth/index-view': RouteRecordInfo<'/auth/index-view', '/auth/index-view', Record<never, never>, Record<never, never>>,
    '/auth/login/login-view': RouteRecordInfo<'/auth/login/login-view', '/auth/login/login-view', Record<never, never>, Record<never, never>>,
    '/auth/login/register-view': RouteRecordInfo<'/auth/login/register-view', '/auth/login/register-view', Record<never, never>, Record<never, never>>,
    '/dashboard/dashboard-view': RouteRecordInfo<'/dashboard/dashboard-view', '/dashboard/dashboard-view', Record<never, never>, Record<never, never>>,
  }
}
